# PHP settings.
php:
  install: yes
  version: 7.4
  composer:
    # List of packages that will be installed globally.
    global:
      - drupal/coder              # PHPCS Drupal standards
      - friendsofphp/php-cs-fixer # PHPCS standard fixer
      - mglaman/drupal-check      # Drupal static code analysis tool

# Node settings.
node:
  install: yes
  version: '--lts' # Use current LTS version.
  npm:
    # List of packages that will be installed globally.
    global: 
      - bower
      - eslint
      - eslint-config-airbnb
      - eslint-config-google
      - eslint-config-standard
      - eslint-plugin-import
      - eslint-plugin-jsx-a11y
      - eslint-plugin-react
      - firebase-tools # Google Firebase tools
      - flow
      - flow-bin
      - gulp
      - lsp
      - vscode-css-languageserver-bin
      - vscode-html-languageserver-bin

python:
  install: yes
  version: 3.8
  pip3:
    # List of packages that will be installed globally.
    global:
      - awscli

# Visual Studio Code settings.
vscode:
  install: yes
  # List of plugins to install.
  plugins:
    - acarreiro.calculate                     # Calculates inline math expr
    - alefragnani.Bookmarks                   # Bookmarks
    - bbeversdorf.drupal-check                # Drupal: check for deprecations
    - christian-kohler.npm-intellisense       # NPM better autocomplete
    - christian-kohler.path-intellisense      # File path autocomplete
    - coenraads.bracket-pair-colorizer        # Bracket Pair Colorizer
    - dbaeumer.vscode-eslint                  # Eslint support
    - editorconfig.editorconfig               # EditorConfig support
    - esbenp.prettier-vscode                  # Prettier - Code formatter
    - github.github-vscode-theme              # GitHub color theme
    - ikappas.composer                        # Composer support
    - mariusschulz.yarn-lock-syntax           # yarn.lock syntax highlight
    - mhutchie.git-graph                      # Git graph
    - mikestead.dotenv                        # .env support
    - ms-azuretools.vscode-docker             # Docker support
    - ms-python.python                        # Python support
    - ms-vscode.go                            # Golang support
    - pkief.material-icon-theme               # Material Icon Theme
    - visualstudioexptteam.vscodeintellicode  # AI-assisted autocomplete
    - william-voyek.vscode-nginx              # nginx.conf support
    - yzhang.markdown-all-in-one              # Markdown tools
    - ikappas.phpcs                           # PHP CodeSniffer

# APT package manager settings.
apps:
  # Add 3rd party apt repos.
  repos:
    - name: 'Microsoft Visual Studio Code'
      filename: vscode
      repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
      gpg: 'https://packages.microsoft.com/keys/microsoft.asc'

    - name: Docker
      filename: docker
      # @TODO: Update when 'focal' repo will be created. 
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
      gpg: 'https://download.docker.com/linux/ubuntu/gpg'

    - name: Google Chrome
      filename: google-chrome
      repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
      gpg: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

    - name: NordVPN
      filename: nordvpn
      repo: 'deb https://repo.nordvpn.com/deb/nordvpn/debian stable main'
      gpg: 'https://repo.nordvpn.com/gpg/nordvpn_public.asc'

    - name: PHP
      filename: php
      repo: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4f4ea0aae5267a6c'

    - name: RetroArch
      filename: retroarch
      repo: 'deb http://ppa.launchpad.net/libretro/stable/ubuntu focal main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x18daae7feca3745f'

    - name: SoftMaker Office
      filename: softmaker-office
      repo: 'deb [arch=amd64] http://shop.softmaker.com/repo/apt wheezy non-free'
      gpg: 'https://shop.softmaker.com/repo/linux-repo-public.key'

    - name: TeamViewer
      filename: teamviewer
      repo: 'deb http://linux.teamviewer.com/deb stable main'
      gpg: 'https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc'


  # List of deb files that should be installed.
  deb:
    - https://download.xnview.com/XnViewMP-linux-x64.deb
    # - https://global.download.synology.com/download/Tools/SynologyDriveClient/2.0.1-11061/Ubuntu/Installer/x86_64/synology-drive-client-11061.x86_64.deb
    - https://zoom.us/client/latest/zoom_amd64.deb # Use deb version of zoom for better Hi-DPI monitor support.

  # List of apt packages to install. Will be installed with all required dependencies.
  apt:
    # System and terminal tools
    - curl        # Command line tool for transferring data with URL syntax
    - default-jdk # Jave development kit
    - default-jre # Java runtime
    - exfat-fuse  # Read and write exFAT driver
    - exfat-utils # Utilities to create, check, label and dump exFAT file system 
    - htop        # Terminal system monitor
    - jq          # JSON query tool
    - lhasa       # lzh unarchiver
    - mc          # Two panel terminal file manager
    - neofetch    # Shows Linux System Information with Distribution Logo
    - net-tools   # Base network tools
    - nfs-common  # Package for work with NFS shares
    - rar         # rar archiver
    - tree        # Displays an indented directory tree, in color
    - unrar       # rar unarchiver
    - unzip       # zip unarchiver
    - zip         # zip archiver

    # Internet
    - firefox              # From Mozilla team with <3
    - google-chrome-stable # Thing for collecting your personal data
    - nordvpn              # NordVPN client
    - teamviewer
    - thunderbird 
    - thunderbird-locale-ru
    - transmission         # Torrent client

    # Office
    - softmaker-freeoffice-2018 # Best free MS Office alternative 
    # - libreoffice
    # - libreoffice-base-drivers
    # - libreoffice-help-en-us
    # - libreoffice-help-ru
    # - libreoffice-l10n-ru
    # - libreoffice-l10n-uk

    # Media
    - dia       # Diagram editor
    - flameshot # Screenshot tool
    - inkscape  # Vector image editor

    # Fonts
    - fonts-dejavu
    - fonts-dejavu-core
    - fonts-dejavu-extra
    - fonts-hack
    - fonts-hack-web
    - fonts-inconsolata
    - fonts-lato
    - fonts-liberation
    - fonts-liberation2
    - fonts-lobster
    - fonts-noto
    - fonts-noto-hinted
    - fonts-noto-mono
    - fonts-noto-unhinted
    - fonts-open-sans
    - fonts-powerline
    - fonts-roboto
    - fonts-roboto-fontface
    - fonts-roboto-unhinted
    - fonts-ubuntu
    - fonts-ubuntu-console

    # Customization
    - papirus-icon-theme

  snap:
    - name: skype
    - name: slack            # Corporate chat
    - name: telegram-desktop # Personal chat
    - name: sublime-text     # Text/code editor
    - name: sublime-merge    # Git GUI
    # - name: icloud-for-linux

    # Jetbrains products
    - name: intellij-idea-community # Jave IDE
    - name: phpstorm                # PHP IDE
    - name: pycharm-community       # Python IDE
    # - name: android-studio          # Android IDE
    # - name: clion                   # C/C++ IDE
    # - name: goland                  # Golang IDE
    # - name: intellij-idea-ultimate  # Java IDE
    # - name: pycharm-professional    # Python IDE
    # - name: rider                   # .NET IDE
    # - name: rubymine                # Ruby IDE
    # - name: space                   # JB Space
    # - name: webstorm                # HTML/JS IDE
