# PHP settings.
php:
  version: '7.3'
  timezone: 'America/New_York'

# Node settings.
node:
  version: '12.14.1'
  npm:
    # List of npm packages that will be installed globally.
    global: [eslint, gulp, bower, eslint-config-google, eslint-config-standard, eslint-config-airbnb, eslint-config-standard, eslint-plugin-jsx-a11y, eslint-plugin-react, eslint-plugin-import]
    
# Visual Studio Code settings.
vscode:
  # List of plugins to install.
  plugins:
    - ms-vscode.go                # Golang
    - ms-python.python            # Python
    - dbaeumer.vscode-eslint      # Eslint
    - esbenp.prettier-vscode      # Prettier - Code formatter
    - pkief.material-icon-theme   # Material Icon Theme
    - dracula-theme.theme-dracula # Dracula theme
    - mikestead.dotenv            # File support .env

# APT package manager settings.
apt:
  repos:
    - name: Docker
      filename: docker
      repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
      gpg: 'https://download.docker.com/linux/ubuntu/gpg'

    - name: Google Chrome
      filename: google-chrome
      repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
      gpg: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

    - name: Numix theme
      filename: numix
      repo: 'deb http://ppa.launchpad.net/numix/ppa/ubuntu bionic main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x43e076121739dee5fb96bbed52b709720f164eeb'

    - name: Papirus icon theme
      filename: papirus
      repo: 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu bionic main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9461999446faf0df770bfc9ae58a9d36647cae7f'

    - name: Yarn
      filename: yarn
      repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
      gpg: 'https://dl.yarnpkg.com/debian/pubkey.gpg'

    - name: Sublime Text & Merge
      filename: sublime
      repo: 'deb https://download.sublimetext.com/ apt/stable/'
      gpg: 'https://download.sublimetext.com/sublimehq-pub.gpg'

  packages:
    install:
      # List of apt packages to install. Will be installed with all required dependencies.
      list:
        # System and terminal tools
        - curl        # Command line tool for transferring data with URL syntax
        - default-jre # Java runtime
        - default-jdk # Jave development kit
        - dia         # Diagram editor
        - exfat-fuse  # Read and write exFAT driver
        - exfat-utils # Utilities to create, check, label and dump exFAT file system 
        - htop        # Terminal system monitor
        - jq          # JSON query tool
        - lhasa       # lzh unarchiver
        - mc          # Two panel terminal file manager
        - neofetch    # Shows Linux System Information with Distribution Logo
        - net-tools   # Base network tools
        - nfs-common  # Package for work with NFS shares
        - python3-pip # Python3 package manager
        - rar         # rar archiver
        - unrar       # rar unarchiver
        - unzip       # zip unarchiver
        - zip         # zip archiver
        - zsh         # zsh shell. Like bash, but better

        # Development
        - mysql-workbench
        - sublime-merge   # Git GUI client
        - sublime-text    # Lightning fast code editor

        # Internet
        - firefox              # From Mozilla team with <3
        - google-chrome-stable # Thing for collecting your personal data
        - telegram-desktop     # Text me, baby!
        
        # Office
        - evolution     # Ultimate email client
        - evolution-ews # Evolution EWS support
        - libreoffice   # Not best, but good office suite
        - libreoffice-help-ru
        - libreoffice-help-en-us
        - libreoffice-base-drivers
        - libreoffice-l10n-ru
        - libreoffice-l10n-uk

        # Media
        #- deepin-picker          # Color picker
        #- deepin-screen-recorder # Screen recorder
        - flameshot              # Screenshot tool
        - inkscape               # Vector image editor

        # KDE-specific packages
        - ksystemlog
        - ksysguard
        - gwenview        # Image browser
        - kget            # Download manager
        - kmahjongg       # Game: Mahjongg
        - kmines          # Game: Minesweeper
        - knights         # Game: Chess
        - kompare         # Diff viewer
        - kpat            # Game: Solitaire 
        - krdc            # RDC/VNC viewer
        - krita           # Image editing software
        - okular          # Document viewer
        - krename         # Mass rename tool
        - krusader        # Two-panel file manager
        - ktorrent        # Torrent downloader
        - kubuntu-restricted-addons # Commonly used restricted packages for Kubuntu
        - kubuntu-restricted-extras # Commonly used media codecs and fonts for Kubuntu
        #- plasma-discover-backend-flatpak # Adds flatpak support to Discover package manager
        #- plasma-discover-backend-snap    # Adds snap support to Discover package manager

        # Look and feel customization packages
        - deepin-icon-theme
        - numix-blue-gtk-theme
        - numix-gtk-theme
        - numix-icon-theme
        - numix-icon-theme-circle
        - papirus-icon-theme

      # List of deb files that should be installed.
      deb:
        # Teamviewer.
        - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.3.2-amd64.deb'
        - https://download.xnview.com/XnViewMP-linux-x64.deb'
        - https://zoom.us/client/latest/zoom_amd64.deb'
        - https://go.skype.com/skypeforlinux-64.deb'
        - https://download.teamviewer.com/download/linux/teamviewer_amd64.deb'

      flathub:
        - org.zealdocs.Zeal # Documentation offline viewer
