# PHP settings.
php:
  install: yes
  version: 7.4
  composer:
    # List of packages that will be installed globally.
    global:
      - drupal/coder

# Node settings.
node:
  install: yes
  version: '--lts' # Use current LTS version.
  npm:
    # List of packages that will be installed globally.
    global: 
      - bower
      - eslint
      - eslint-config-airbnb
      - eslint-config-google
      - eslint-config-standard
      - eslint-plugin-import
      - eslint-plugin-jsx-a11y
      - eslint-plugin-react
      - firebase-tools # Google Firebase tools
      - flow
      - flow-bin
      - gulp
      - lsp
      - vscode-css-languageserver-bin
      - vscode-html-languageserver-bin

python:
  install: yes
  version: 3.8
  pip3:
    # List of packages that will be installed globally.
    global:
      - awscli

# Visual Studio Code settings.
vscode:
  install: yes
  # List of plugins to install.
  plugins:
    - ms-vscode.go                # Golang
    - ms-python.python            # Python
    - dbaeumer.vscode-eslint      # Eslint
    - esbenp.prettier-vscode      # Prettier - Code formatter
    - pkief.material-icon-theme   # Material Icon Theme
    - dracula-theme.theme-dracula # Dracula theme
    - mikestead.dotenv            # File support for .env

# APT package manager settings.
apt:
  # Add 3rd party apt repos.
  repos:
    - name: Docker
      filename: docker
      # @TODO: Update when 'focal' repo will be created. 
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
      gpg: 'https://download.docker.com/linux/ubuntu/gpg'

    - name: Google Chrome
      filename: google-chrome
      repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
      gpg: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

    - name: NordVPN
      filename: nordvpn
      repo: 'deb https://repo.nordvpn.com/deb/nordvpn/debian stable main'
      gpg: 'https://repo.nordvpn.com/gpg/nordvpn_public.asc'

    - name: PHP
      filename: php
      repo: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4f4ea0aae5267a6c'

    - name: RetroArch
      filename: retroarch
      repo: 'deb http://ppa.launchpad.net/libretro/stable/ubuntu focal main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x18daae7feca3745f'
 
    - name: SoftMaker Office
      filename: softmaker-office
      repo: 'deb [arch=amd64] http://shop.softmaker.com/repo/apt wheezy non-free'
      gpg: 'https://shop.softmaker.com/repo/linux-repo-public.key'

  # List of deb files that should be installed.
  deb:
    - https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
    - https://download.xnview.com/XnViewMP-linux-x64.deb
    - https://global.download.synology.com/download/Tools/SynologyDriveClient/2.0.1-11061/Ubuntu/Installer/x86_64/synology-drive-client-11061.x86_64.deb

  # List of apt packages to install. Will be installed with all required dependencies.
  install:
    # System and terminal tools
    - curl        # Command line tool for transferring data with URL syntax
    - default-jdk # Jave development kit
    - default-jre # Java runtime
    - exfat-fuse  # Read and write exFAT driver
    - exfat-utils # Utilities to create, check, label and dump exFAT file system 
    - htop        # Terminal system monitor
    - jq          # JSON query tool
    - lhasa       # lzh unarchiver
    - mc          # Two panel terminal file manager
    - neofetch    # Shows Linux System Information with Distribution Logo
    - net-tools   # Base network tools
    - nfs-common  # Package for work with NFS shares
    - nordvpn     # NordVPN client
    - rar         # rar archiver
    - tree        # Displays an indented directory tree, in color
    - unrar       # rar unarchiver
    - unzip       # zip unarchiver
    - zip         # zip archiver

    # Internet
    - evolution     # Email client
    - evolution-ews # Microsoft Exchange services support
    - firefox              # From Mozilla team with <3
    - google-chrome-stable # Thing for collecting your personal data
    - transmission         # Torrent client
    # - thunderbird 
    # - thunderbird-locale-ru

    # Office
    - softmaker-freeoffice-2018 # Best free MS Office alternative 
    # - libreoffice
    # - libreoffice-base-drivers
    # - libreoffice-help-en-us
    # - libreoffice-help-ru
    # - libreoffice-l10n-ru
    # - libreoffice-l10n-uk

    # Media
    - dia       # Diagram editor
    - flameshot # Screenshot tool
    - inkscape  # Vector image editor

    # Icons
    - adwaita-icon-theme-full
    - deepin-icon-theme
    - numix-icon-theme
    - numix-icon-theme-circle
    - papirus-icon-theme

    # Fonts
    - fonts-dejavu
    - fonts-dejavu-core
    - fonts-dejavu-extra
    - fonts-hack
    - fonts-hack-web
    - fonts-inconsolata
    - fonts-lato
    - fonts-liberation
    - fonts-liberation2
    - fonts-lobster
    - fonts-noto
    - fonts-noto-hinted
    - fonts-noto-mono
    - fonts-noto-unhinted
    - fonts-open-sans
    - fonts-powerline
    - fonts-roboto
    - fonts-roboto-fontface
    - fonts-roboto-unhinted
    - fonts-ubuntu
    - fonts-ubuntu-console

snap:
  install:
    - name: skype
    - name: slack            # Corporate chat
    - name: telegram-desktop # Personal chat
    - name: zoom-client      # Zoom.us client
    - name: sublime-text     # Text/code editor
    - name: sublime-merge    # Git GUI
    - name: zeal-casept      # Offline documentation viewer
    # - name: icloud-for-linux
    #   classic: yes
    #   channel: latest

    # Jetbrains products
    - name: intellij-idea-community # Jave IDE
    - name: phpstorm                # PHP IDE
    - name: pycharm-community       # Python IDE
    # - name: android-studio          # Android IDE
    # - name: clion                   # C/C++ IDE
    # - name: goland                  # Golang IDE
    # - name: intellij-idea-ultimate  # Java IDE
    # - name: pycharm-professional    # Python IDE
    # - name: rider                   # .NET IDE
    # - name: rubymine                # Ruby IDE
    # - name: space                   # JB Space
    # - name: webstorm                # HTML/JS IDE

# Ubuntu Gnome specific configuration.
# Note: it should be applied ONLY to regular Ubuntu installation.
gnome:
  apply: yes
  apt:
    install:
      - gnome-tweaks
      - ubuntu-restricted-addons
      - ubuntu-restricted-extras

      # Themes
      - adapta-gtk-theme
      - materia-gtk-theme
      - arc-theme
      - numix-blue-gtk-theme
      - numix-gtk-theme
  extensions:
    - id: 19   # User Themes for Gnome Shell
      enable: yes
    - id: 258  # Notifications Alert
      enable: yes
    - id: 307  # Dash to Dock
      enable: yes
    - id: 906  # Sound Input & Output Device Chooser
      enable: yes
    - id: 1040 # Random wallpaper
      enable: yes
    - id: 1228 # Arc Menu
      enable: yes
    - id: 1251 # Blyr
      enable: yes
    - id: 1287 # Unite
      enable: no
  gsettings: []
  dconf: []

# KDE-specific configuration.
# Note: it should be applied ONLY to KUbuntu installation.
kde:
  apply: no
  apt:
    install:
      - gwenview   # Image browser
      - kcalc      # Calculator
      - kget       # Download manager
      - kmahjongg  # Game: Mahjongg
      - kmines     # Game: Minesweeper
      - knights    # Game: Chess
      - kompare    # Diff viewer
      - kpat       # Game: Solitaire 
      - krdc       # RDC/VNC viewer
      - krename    # Mass rename tool
      - krita      # Image editing software
      - krusader   # Two-panel file manager
      - ksysguard  # System monitor
      - ksystemlog # System logs viewer
      - okular     # Document viewer
      - kubuntu-restricted-addons
      - kubuntu-restricted-extras

      # KDE themes
      - adapta-kde
      - arc-kde
      - materia-kde
