# ZSH settings.
zsh:
  install: yes
  theme: avit
  antigen_bundles:
    - name: git
    - name: command-not-found
    - name: zsh-autosuggestions
      url: zsh-users/zsh-autosuggestions
    - name: zsh-nvm
      url: lukechilds/zsh-nvm

# Node settings.
node:
  install: yes
  version: '12.14.1'
  npm:
    # List of npm packages that will be installed globally.
    global: [eslint, gulp, bower, eslint-config-google, eslint-config-standard, eslint-config-airbnb, eslint-config-standard, eslint-plugin-jsx-a11y, eslint-plugin-react, eslint-plugin-import]
    
# Visual Studio Code settings.
vscode:
  install: yes
  # List of plugins to install.
  plugins:
    - ms-vscode.go                # Golang
    - ms-python.python            # Python
    - dbaeumer.vscode-eslint      # Eslint
    - esbenp.prettier-vscode      # Prettier - Code formatter
    - pkief.material-icon-theme   # Material Icon Theme
    - dracula-theme.theme-dracula # Dracula theme
    - mikestead.dotenv            # File support .env

# APT package manager settings.
apt:
  repos:
    - name: Docker
      filename: docker
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
      gpg: 'https://download.docker.com/linux/ubuntu/gpg'

    - name: Google Chrome
      filename: google-chrome
      repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
      gpg: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

    - name: Numix theme
      filename: numix
      repo: 'deb http://ppa.launchpad.net/numix/ppa/ubuntu bionic main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x43e076121739dee5fb96bbed52b709720f164eeb'

    - name: Papirus icon theme
      filename: papirus
      repo: 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu bionic main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9461999446faf0df770bfc9ae58a9d36647cae7f'

    - name: Yarn
      filename: yarn
      repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
      gpg: 'https://dl.yarnpkg.com/debian/pubkey.gpg'

    - name: Visual Studio Code
      filename: vscode
      repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
      gpg: 'https://packages.microsoft.com/keys/microsoft.asc'
      
    - name: Sublime Text & Merge
      filename: sublime
      repo: 'deb https://download.sublimetext.com/ apt/stable/'
      gpg: 'https://download.sublimetext.com/sublimehq-pub.gpg'

    - name: PHP
      filename: php
      repo: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c'

  packages:
    install:
      # List of apt packages to install. Will be installed with all required dependencies.
      list:
        # System and terminal tools
        - curl        # Command line tool for transferring data with URL syntax
        - default-jdk # Jave development kit
        - default-jre # Java runtime
        - dia         # Diagram editor
        - exfat-fuse  # Read and write exFAT driver
        - exfat-utils # Utilities to create, check, label and dump exFAT file system 
        - htop        # Terminal system monitor
        - jq          # JSON query tool
        - lhasa       # lzh unarchiver
        - mc          # Two panel terminal file manager
        - neofetch    # Shows Linux System Information with Distribution Logo
        - net-tools   # Base network tools
        - nfs-common  # Package for work with NFS shares
        - python3-pip # Python3 package manager
        - rar         # rar archiver
        - tree        # Displays an indented directory tree, in color
        - unrar       # rar unarchiver
        - unzip       # zip unarchiver
        - zip         # zip archiver
        - zsh         # zsh shell. Like bash, but better

        # PHP 7.3
        - php7.3-common
        - php7.3-cli
        - php7.3-curl
        - php7.3-gd
        - php7.3-json
        - php7.3-mbstring
        - php7.3-mysql
        - php7.3-opcache
        - php7.3-xml
        - php7.3-zip

        # Development
        - mysql-workbench
        - sublime-merge   # Git GUI client
        - sublime-text    # Lightning fast code editor

        # Internet
        - firefox              # From Mozilla team with <3
        - google-chrome-stable # Thing for collecting your personal data
        - qbittorrent          # Best torrent downloading ever
        
        # Office
        # - evolution     # Email client
        # - evolution-ews # Microsoft Exchange services support
        - libreoffice     # Not best, but good office suite
        - libreoffice-base-drivers
        - libreoffice-help-en-us
        - libreoffice-help-ru
        - libreoffice-l10n-ru
        - libreoffice-l10n-uk
        - thunderbird
        - thunderbird-locale-ru

        # Media
        #- deepin-picker          # Color picker
        #- deepin-screen-recorder # Screen recorder
        - flameshot              # Screenshot tool
        - inkscape               # Vector image editor

        # KDE-specific packages
        - gwenview        # Image browser
        - kcalc           # Calculator
        - kget            # Download manager
        - kmahjongg       # Game: Mahjongg
        - kmines          # Game: Minesweeper
        - knights         # Game: Chess
        - kompare         # Diff viewer
        - kpat            # Game: Solitaire 
        - krdc            # RDC/VNC viewer
        - krename         # Mass rename tool
        - krita           # Image editing software
        - krusader        # Two-panel file manager
        - ksysguard       # System monitor
        - ksystemlog      # System logs viewer
        - okular          # Document viewer
        - kubuntu-restricted-addons # Commonly used restricted packages for Kubuntu
        - kubuntu-restricted-extras # Commonly used media codecs and fonts for Kubuntu
        #- plasma-discover-backend-flatpak # Adds flatpak support to Discover package manager
        #- plasma-discover-backend-snap    # Adds snap support to Discover package manager

        # Look and feel customization packages
        - deepin-icon-theme
        - numix-blue-gtk-theme
        - numix-gtk-theme
        - numix-icon-theme
        - numix-icon-theme-circle
        - papirus-icon-theme
        - adwaita-icon-theme

        # Fonts.
        - fonts-dejavu
        - fonts-dejavu-core
        - fonts-dejavu-extra
        - fonts-hack
        - fonts-hack-web
        - fonts-inconsolata
        - fonts-lato
        - fonts-liberation
        - fonts-liberation2
        - fonts-lobster
        - fonts-noto
        - fonts-noto-hinted
        - fonts-noto-mono
        - fonts-noto-unhinted
        - fonts-open-sans
        - fonts-powerline
        - fonts-roboto
        - fonts-roboto-fontface
        - fonts-roboto-unhinted
        - fonts-ubuntu
        - fonts-ubuntu-console

      # List of deb files that should be installed.
      deb:
        - https://download.teamviewer.com/download/linux/teamviewer_amd64.deb

      flathub:
        - org.zealdocs.Zeal # Documentation offline viewer
        - org.telegram.desktop
        - com.skype.Client
        - com.xnview.XnViewMP
        - us.zoom.Zoom
        - com.slack.Slack
