# PHP settings.
php:
  install: yes
  version: 7.4
  composer:
    # List of packages that will be installed globally.
    global:
      - drupal/coder

# Node settings.
node:
  install: yes
  version: '--lts' # Use current LTS version.
  npm:
    # List of packages that will be installed globally.
    global: 
      - bower
      - eslint
      - eslint-config-airbnb
      - eslint-config-google
      - eslint-config-standard
      - eslint-plugin-import
      - eslint-plugin-jsx-a11y
      - eslint-plugin-react
      - firebase-tools # Google Firebase tools
      - flow
      - flow-bin
      - gulp
      - lsp
      - vscode-css-languageserver-bin
      - vscode-html-languageserver-bin

python:
  install: yes
  version: 3.8
  pip3:
    # List of packages that will be installed globally.
    global:
      - awscli

# Visual Studio Code settings.
vscode:
  install: yes
  # List of plugins to install.
  plugins:
    - christian-kohler.npm-intellisense       # NPM better autocomplete
    - christian-kohler.path-intellisense      # File path autocomplete
    - coenraads.bracket-pair-colorizer        # Bracket Pair Colorizer
    - dbaeumer.vscode-eslint                  # Eslint support
    - editorconfig.editorconfig               # EditorConfig support
    - esbenp.prettier-vscode                  # Prettier - Code formatter
    - fkrull.gtk-dark-titlebar                # GTK Dark Title Bar
    - mariusschulz.yarn-lock-syntax           # yarn.lock syntax highlight
    - mhutchie.git-graph                      # Git graph
    - mikestead.dotenv                        # .env support
    - ms-azuretools.vscode-docker             # Docker support
    - ms-python.python                        # Python support
    - ms-vscode.go                            # Golang support
    - pkief.material-icon-theme               # Material Icon Theme
    - rafaelmardojai.vscode-gnome-theme       # A GNOME color theme
    - visualstudioexptteam.vscodeintellicode  # AI-assisted autocomplete
    - william-voyek.vscode-nginx              # nginx.conf support
    - yzhang.markdown-all-in-one              # Markdown tools

# APT package manager settings.
apps:
  # Add 3rd party apt repos.
  repos:
    - name: Docker
      filename: docker
      # @TODO: Update when 'focal' repo will be created. 
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
      gpg: 'https://download.docker.com/linux/ubuntu/gpg'

    - name: Google Chrome
      filename: google-chrome
      repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
      gpg: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

    - name: NordVPN
      filename: nordvpn
      repo: 'deb https://repo.nordvpn.com/deb/nordvpn/debian stable main'
      gpg: 'https://repo.nordvpn.com/gpg/nordvpn_public.asc'

    - name: PHP
      filename: php
      repo: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4f4ea0aae5267a6c'

    - name: RetroArch
      filename: retroarch
      repo: 'deb http://ppa.launchpad.net/libretro/stable/ubuntu focal main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x18daae7feca3745f'

    - name: SoftMaker Office
      filename: softmaker-office
      repo: 'deb [arch=amd64] http://shop.softmaker.com/repo/apt wheezy non-free'
      gpg: 'https://shop.softmaker.com/repo/linux-repo-public.key'

    - name: TeamViewer
      filename: teamviewer
      repo: 'deb http://linux.teamviewer.com/deb stable main'
      gpg: 'https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc'


  # List of deb files that should be installed.
  deb:
    - https://download.xnview.com/XnViewMP-linux-x64.deb
    # - https://global.download.synology.com/download/Tools/SynologyDriveClient/2.0.1-11061/Ubuntu/Installer/x86_64/synology-drive-client-11061.x86_64.deb
    - https://zoom.us/client/latest/zoom_amd64.deb # Use deb version of zoom for better Hi-DPI monitor support.

  # List of apt packages to install. Will be installed with all required dependencies.
  apt:
    # System and terminal tools
    - curl        # Command line tool for transferring data with URL syntax
    - default-jdk # Jave development kit
    - default-jre # Java runtime
    - exfat-fuse  # Read and write exFAT driver
    - exfat-utils # Utilities to create, check, label and dump exFAT file system 
    - htop        # Terminal system monitor
    - jq          # JSON query tool
    - lhasa       # lzh unarchiver
    - mc          # Two panel terminal file manager
    - neofetch    # Shows Linux System Information with Distribution Logo
    - net-tools   # Base network tools
    - nfs-common  # Package for work with NFS shares
    - rar         # rar archiver
    - tree        # Displays an indented directory tree, in color
    - unrar       # rar unarchiver
    - unzip       # zip unarchiver
    - zip         # zip archiver

    # Internet
    - firefox              # From Mozilla team with <3
    - google-chrome-stable # Thing for collecting your personal data
    - nordvpn              # NordVPN client
    - teamviewer
    - thunderbird 
    - thunderbird-locale-ru
    - transmission         # Torrent client

    # Office
    - softmaker-freeoffice-2018 # Best free MS Office alternative 
    # - libreoffice
    # - libreoffice-base-drivers
    # - libreoffice-help-en-us
    # - libreoffice-help-ru
    # - libreoffice-l10n-ru
    # - libreoffice-l10n-uk

    # Media
    - dia       # Diagram editor
    - flameshot # Screenshot tool
    - inkscape  # Vector image editor

    # Fonts
    - fonts-dejavu
    - fonts-dejavu-core
    - fonts-dejavu-extra
    - fonts-hack
    - fonts-hack-web
    - fonts-inconsolata
    - fonts-lato
    - fonts-liberation
    - fonts-liberation2
    - fonts-lobster
    - fonts-noto
    - fonts-noto-hinted
    - fonts-noto-mono
    - fonts-noto-unhinted
    - fonts-open-sans
    - fonts-powerline
    - fonts-roboto
    - fonts-roboto-fontface
    - fonts-roboto-unhinted
    - fonts-ubuntu
    - fonts-ubuntu-console

  snap:
    - name: skype
    - name: slack            # Corporate chat
    - name: telegram-desktop # Personal chat
    - name: sublime-text     # Text/code editor
    - name: sublime-merge    # Git GUI
    - name: zeal-casept      # Offline documentation viewer
    # - name: icloud-for-linux
    #   classic: yes
    #   channel: latest

    # Jetbrains products
    - name: intellij-idea-community # Jave IDE
    - name: phpstorm                # PHP IDE
    - name: pycharm-community       # Python IDE
    # - name: android-studio          # Android IDE
    # - name: clion                   # C/C++ IDE
    # - name: goland                  # Golang IDE
    # - name: intellij-idea-ultimate  # Java IDE
    # - name: pycharm-professional    # Python IDE
    # - name: rider                   # .NET IDE
    # - name: rubymine                # Ruby IDE
    # - name: space                   # JB Space
    # - name: webstorm                # HTML/JS IDE

# Ubuntu Gnome specific configuration.
gnome:
  apply: yes
  apt:
    - gnome-tweaks
    - ubuntu-restricted-addons
    - ubuntu-restricted-extras

    # Themes
    - adapta-gtk-theme
    - materia-gtk-theme
    - arc-theme
    - numix-blue-gtk-theme
    - numix-gtk-theme

    # Icons
    - papirus-icon-theme

    # Cursors
    - oxygen-cursor-theme
  extensions:
    - { id: 258,  enable: yes } # Notifications Alert
    - { id: 307,  enable: yes } # Dash to Dock
    - { id: 906,  enable: yes } # Sound Input & Output Device Chooser
    - { id: 1040, enable: yes } # Random wallpaper
    - { id: 1251, enable: yes } # Blyr
  gsettings:
    # Desktop customization
    - org.gnome.desktop.interface icon-theme "Papirus"
    - org.gnome.desktop.interface cursor-theme "oxy-white"
    
    # Disable paste on middle click
    - org.gnome.desktop.interface gtk-enable-primary-paste false
    
    # Monospace font and size
    - org.gnome.desktop.interface monospace-font-name "JetBrains Mono 12"
    
    # Disable lock on suspend
    - org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
    
    # Time before session is considered idle (seconds)
    - org.gnome.desktop.session idle-delay 1800
    
    # Files: Enable tree in list view
    - 'org.gnome.nautilus.list-view use-tree-view true'
    
    # Terminal: menu accelerator key (F10)
    - org.gnome.Terminal.Legacy.Settings menu-accelerator-enabled false
    
    # Dash to dock settings
    - org.gnome.shell.extensions.dash-to-dock autohide true
    - org.gnome.shell.extensions.dash-to-dock autohide-in-fullscreen false
    - org.gnome.shell.extensions.dash-to-dock click-action "minimize-or-previews"
    - org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 36
    - org.gnome.shell.extensions.dash-to-dock dock-fixed true
    - org.gnome.shell.extensions.dash-to-dock extend-height true
    - org.gnome.shell.extensions.dash-to-dock hide-delay 0.2
    - org.gnome.shell.extensions.dash-to-dock intellihide true
    - org.gnome.shell.extensions.dash-to-dock intellihide-mode "FOCUS_APPLICATION_WINDOWS"
    - org.gnome.shell.extensions.dash-to-dock pressure-threshold 100
    - org.gnome.shell.extensions.dash-to-dock require-pressure-to-show true
    - org.gnome.shell.extensions.dash-to-dock show-apps-at-top false
    - org.gnome.shell.extensions.dash-to-dock show-delay 0.25
    - org.gnome.shell.extensions.dash-to-dock show-mounts false
    - org.gnome.shell.extensions.dash-to-dock show-trash false
