php:
  install: yes
  version: 7.4
  # @TODO: Add composer version select: v1 or v2.
  composer:
    # List of global composer packages to install.
    global:
      - drush/drush
      - squizlabs/php_codesniffer
      - drupal/coder              # PHPCS Drupal standards
      - friendsofphp/php-cs-fixer # PHPCS standard fixer
      - mglaman/drupal-check      # Drupal static code analysis tool

node:
  install: yes
  version: '--lts' # Use current LTS version.
  npm:
    # List of global npm packages to install.
    global: 
      - bower
      - eslint
      - eslint-config-airbnb
      - eslint-config-google
      - eslint-config-standard
      - eslint-plugin-import
      - eslint-plugin-jsx-a11y
      - eslint-plugin-react
      - firebase-tools # Google Firebase tools.
      - flow
      - flow-bin
      - gulp
      - lsp
      - typescript
      - vscode-css-languageserver-bin
      - vscode-html-languageserver-bin
      - yarn

python:
  install: yes
  version: 3.8
  pip3:
    # List of global packages to install.
    global:
      - awscli

vscode:
  install: yes
  # List of plugins to install.
  extensions:
    - acarreiro.calculate                     # Calculates inline math expr
    - alefragnani.Bookmarks                   # Bookmarks
    - bbeversdorf.drupal-check                # Drupal: check for deprecations
    - christian-kohler.npm-intellisense       # NPM better autocomplete
    - christian-kohler.path-intellisense      # File path autocomplete
    - coenraads.bracket-pair-colorizer        # Bracket Pair Colorizer
    - dbaeumer.vscode-eslint                  # Eslint support
    - editorconfig.editorconfig               # EditorConfig support
    - esbenp.prettier-vscode                  # Prettier - Code formatter
    - github.github-vscode-theme              # GitHub color theme
    - golang.go                               # Golang support
    - ikappas.composer                        # Composer support
    - ikappas.phpcs                           # PHP CodeSniffer
    - mariusschulz.yarn-lock-syntax           # yarn.lock syntax highlight
    - mhutchie.git-graph                      # Git graph
    - mikestead.dotenv                        # .env support
    - ms-azuretools.vscode-docker             # Docker support
    - ms-python.python                        # Python support
    - pkief.material-icon-theme               # Material Icon Theme
    - visualstudioexptteam.vscodeintellicode  # AI-assisted autocomplete
    - william-voyek.vscode-nginx              # nginx.conf support
    - yzhang.markdown-all-in-one              # Markdown tools
    - hookyqr.beautify                        # HTML/JSON beautifier
    - dakara.transformer                      # Filter, Sort, Unique, Reverse, Align, CSV, Line Selection, Text Transformations and Macros

apps:
  # List of 3rd party apt repos to add.
  repos:
    - name: 'Microsoft Visual Studio Code'
      filename: vscode
      repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
      gpg: 'https://packages.microsoft.com/keys/microsoft.asc'

    - name: Docker
      filename: docker
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
      gpg: 'https://download.docker.com/linux/ubuntu/gpg'

    - name: Google Chrome
      filename: google-chrome
      repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
      gpg: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

    - name: NordVPN
      filename: nordvpn
      repo: 'deb https://repo.nordvpn.com/deb/nordvpn/debian stable main'
      gpg: 'https://repo.nordvpn.com/gpg/nordvpn_public.asc'

    - name: PHP
      filename: php
      repo: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main'
      gpg: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4f4ea0aae5267a6c'

    - name: Sublime Apps
      filename: sublime
      repo: 'deb https://download.sublimetext.com/ apt/stable/'
      gpg: 'https://download.sublimetext.com/sublimehq-pub.gpg'

    - name: TeamViewer
      filename: teamviewer
      repo: 'deb http://linux.teamviewer.com/deb stable main'
      gpg: 'https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc'

  # List of *.deb URLs to install.
  deb:
    - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.8.0-amd64.deb
    - https://global.download.synology.com/download/Tools/SynologyDriveClient/2.0.1-11061/Ubuntu/Installer/x86_64/synology-drive-client-11061.x86_64.deb
    - https://zoom.us/client/latest/zoom_amd64.deb # Use deb version of zoom for better Hi-DPI monitor support.

  # List of apt packages to install.
  apt:
    # System and terminal tools
    - curl        # Command line tool for transferring data with URL syntax
    - default-jdk # Jave development kit
    - default-jre # Java runtime
    - exfat-fuse  # Read and write exFAT driver
    - exfat-utils # Utilities to create, check, label and dump exFAT file system 
    - heif-gdk-pixbuf  # Apple HEIF/HEIC decoder support 
    - heif-thumbnailer # Apple HEIF/HEIC thumbnails support 
    - htop        # Terminal system monitor
    - jq          # JSON query tool
    - lhasa       # lzh unarchiver
    - mc          # Two panel terminal file manager
    - neofetch    # Shows Linux System Information with Distribution Logo
    - net-tools   # Base network tools
    - nfs-common  # Package for work with NFS shares
    - rar         # rar archiver
    - tree        # Displays an indented directory tree, in color
    - unrar       # rar unarchiver
    - unzip       # zip unarchiver
    - zip         # zip archiver

    # Internet
    - firefox              # From Mozilla team with <3
    - google-chrome-stable # Thing for collecting your personal data
    - nordvpn              # NordVPN client
    - teamviewer
    - telegram-desktop
    - thunderbird
    - thunderbird-locale-ru
    - transmission         # Torrent client

    # Office
    - libreoffice
    - libreoffice-base-drivers
    - libreoffice-help-en-us
    - libreoffice-help-ru
    - libreoffice-l10n-ru
    - libreoffice-l10n-uk
    - sublime-merge # Git GUI
    - sublime-text  # Text/code editor

    # Media
    - clementine # Audio/Radio/Podcasts player
    - dia        # Diagram editor
    - flameshot  # Screenshot tool
    - inkscape   # Vector image editor
    - vlc        # Legend!

    # Fonts
    - fonts-dejavu
    - fonts-dejavu-core
    - fonts-dejavu-extra
    - fonts-hack
    - fonts-hack-web
    - fonts-inconsolata
    - fonts-lato
    - fonts-liberation
    - fonts-liberation2
    - fonts-lobster
    - fonts-noto
    - fonts-noto-hinted
    - fonts-noto-mono
    - fonts-noto-unhinted
    - fonts-open-sans
    - fonts-powerline
    - fonts-roboto
    - fonts-roboto-fontface
    - fonts-roboto-unhinted
    - fonts-ubuntu
    - fonts-ubuntu-console

    # Customization
    - papirus-icon-theme

  flatpak:
    - com.getpostman.Postman
