apps:
  # List of 3rd party apt repos to add.
  repos:
    vscode:
      repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
      gpg: 'https://packages.microsoft.com/keys/microsoft.asc'
    docker:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
      gpg: 'https://download.docker.com/linux/ubuntu/gpg'
    google-chrome:
      repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
      gpg: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
    nordvpn:
      repo: 'deb https://repo.nordvpn.com/deb/nordvpn/debian stable main'
      gpg: 'https://repo.nordvpn.com/gpg/nordvpn_public.asc'
    php:
      repo: 'ppa:ondrej/php'
    sublime:
      repo: 'deb https://download.sublimetext.com/ apt/stable/'
      gpg: 'https://download.sublimetext.com/sublimehq-pub.gpg'

  # List of *.deb URLs to install.
  deb:
   - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.11.3-amd64.deb
   - https://global.download.synology.com/download/Utility/SynologyDriveClient/2.0.2-11078/Ubuntu/Installer/x86_64/synology-drive-client-11078.x86_64.deb
   - https://repo.skype.com/latest/skypeforlinux-64.deb
   - https://zoom.us/client/latest/zoom_amd64.deb
   - https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
   #- https://download.xnview.com/XnViewMP-linux-x64.deb

  # List of apt packages to install.
  apt:
    # System/CLI apps
    - curl        # Command line tool for transferring data with URL syntax
    - default-jdk # Jave development kit
    - default-jre # Java runtime
    - exfat-fuse  # Read and write exFAT driver
    - exfat-utils # Utilities to create, check, label and dump exFAT file system 
    - heif-gdk-pixbuf  # Apple HEIF/HEIC decoder support 
    - heif-thumbnailer # Apple HEIF/HEIC thumbnails support 
    - htop        # Terminal system monitor
    - jq          # Takes JSON input and retrieves data by query.
    - mc          # Two panel terminal file manager
    - neofetch    # Shows Linux System Information with Distribution Logo
    - net-tools   # Base network tools
    - nfs-common  # Package for work with NFS shares
    - stacer      # Cool CleanMyMac alternative
    - tree        # Displays an indented directory tree, in color
  
    # Archive formats support
    - arj         # arj archiver
    - lhasa       # lzh unarchiver
    - rar         # rar archiver
    - unrar       # rar unarchiver
    - unzip       # zip unarchiver
    - zip         # zip archiver

    # Office
    - libreoffice
    - libreoffice-base-drivers # Base drivers
    - libreoffice-help-en-us   # Help: English
    - libreoffice-help-ru      # Help: Russian
    - libreoffice-l10n-ru      # Localization: Russian
    - libreoffice-l10n-uk      # Localization: Ukrainian

    # Web browsers
    - firefox              # From Mozilla team with <3
    - google-chrome-stable # Thing for collecting your personal data

    - clementine           # Audio/Radio/Podcasts player
    - dia                  # Diagram editor
    - evolution            # Outlook alternative
    - evolution-ews        # Evolution Exchange support
    - flameshot            # Screenshot tool
    - inkscape             # Vector image editor
    - nordvpn              # NordVPN client
    - qbittorrent          # Torrent client
    - sublime-merge        # Git GUI
    - sublime-text         # Text/code editor
    - teamviewer           # Remote administration
    - telegram-desktop     # Best IM
    - vlc                  # Legend!

    # KDE apps
    - kompare  # File difference viewer
    - krename  # Batch renamer for KDE
    - krusader # Two-panel file manager
    - okular   # Universal document viewer
    - yakuake  # Quake-style dropdown terminal

    # Fonts
    - fonts-dejavu
    - fonts-hack
    - fonts-open-sans
    - fonts-roboto
    - fonts-ubuntu

    # Customization
    - papirus-icon-theme

  flatpak:
    - com.getpostman.Postman # API debugging tool
    - com.github.johnfactotum.Foliate # eBook reader
    # - com.discordapp.Discord
    # - com.rafaelmardojai.Blanket # Listen to different sounds
    # - com.spotify.Client

php:
  install: yes
  version: 7.4
  # @TODO: Add composer version select: v1 or v2.
  composer:
    # List of global composer packages to install.
    global:
      - drush/drush
      - squizlabs/php_codesniffer
      - drupal/coder              # PHPCS Drupal standards
      - friendsofphp/php-cs-fixer # PHPCS standard fixer
      - mglaman/drupal-check      # Drupal static code analysis tool

node:
  install: yes
  version: '--lts' # Use current LTS version.
  npm:
    # List of global npm packages to install.
    global: 
      - bower
      - eslint
      - eslint-config-airbnb
      - eslint-config-google
      - eslint-config-standard
      - eslint-plugin-import
      - eslint-plugin-jsx-a11y
      - eslint-plugin-react
      - firebase-tools
      - flow
      - flow-bin
      - gulp
      - lsp
      - typescript
      - vscode-css-languageserver-bin
      - vscode-html-languageserver-bin
      - yarn

python:
  install: yes
  version: 3.8
  pip3:
    # List of global packages to install.
    global:
      - awscli # AWS cli.
      - yq     # Takes YAML input and retrieves data by query.

vscode:
  install: yes
  # List of plugins to install.
  extensions:
    - acarreiro.calculate                # Calculates inline math expr
    - christian-kohler.path-intellisense # File path autocomplete
    - coenraads.bracket-pair-colorizer   # Bracket Pair Colorizer
    - dakara.transformer                 # Filter, Sort, Unique, Reverse, Align, CSV, Line Selection, Text Transformations and Macros
    - editorconfig.editorconfig          # EditorConfig support
    - esbenp.prettier-vscode             # Prettier - Code formatter
    - github.github-vscode-theme         # GitHub color theme
    - golang.go                          # Golang support
    - hookyqr.beautify                   # HTML/JSON beautifier
    - mhutchie.git-graph                 # Git graph
    - mikestead.dotenv                   # .env support
    - ms-azuretools.vscode-docker        # Docker support
    - ms-python.python                   # Python support
    - pkief.material-icon-theme          # Material Icon Theme
    - TabNine.tabnine-vscode             # AI-assisted autocomplete
    - tyriar.lorem-ipsum                 # Lorem Ipsum generator
    - william-voyek.vscode-nginx         # nginx.conf support
    - yzhang.markdown-all-in-one         # Markdown tools
    #- alefragnani.Bookmarks             # Bookmarks

    # Node/NPM/Yarn specific extensions
    - christian-kohler.npm-intellisense # NPM better autocomplete
    - dbaeumer.vscode-eslint            # Eslint support
    - mariusschulz.yarn-lock-syntax     # yarn.lock syntax highlight

    # PHP/Drupal specific extensions
    - bbeversdorf.drupal-check # Drupal: check for deprecations
    - ikappas.composer         # Composer support
    - ikappas.phpcs            # PHP CodeSniffer

jetbrains:
  toolbox:
    install: yes
