# PHP settings.
php:
  version: '7.3'
  timezone: 'America/New_York'

# Node settings.
node:
  version: '12.14.1'
  npm:
    # List of npm packages that will be installed globally.
    global: [eslint, gulp, bower, eslint-config-google, eslint-config-standard, eslint-config-airbnb, eslint-config-standard, eslint-plugin-jsx-a11y, eslint-plugin-react, eslint-plugin-import]
    
# Visual Studio Code settings.
vscode:
  # List of plugins to install.
  plugins:
    - ms-vscode.go # Golang
    - ms-python.python # Python
    - dbaeumer.vscode-eslint # Eslint
    - esbenp.prettier-vscode # Prettier - Code formatter
    - pkief.material-icon-theme # Material Icon Theme
    - dracula-theme.theme-dracula # Dracula theme
    - mikestead.dotenv # File support .env

# APT package manager settings.
apt:
  # List of repos that should be added. If repo has gpg key it has to be added as well, otherwise repo will not work. 
  repos:
    - name: Google Chrome
      filename: google-chrome
      repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
      gpg: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

    - name: Numix theme
      filename: numix
      repo: 'ppa:numix/ppa'

    - name: Papirus icon theme
      filename: papirus
      repo: 'ppa:papirus/papirus'

    - name: Yarn
      filename: yarn
      repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
      gpg: 'https://dl.yarnpkg.com/debian/pubkey.gpg'

    - name: Sublime Text & Merge
      filename: sublime
      repo: 'deb https://download.sublimetext.com/ apt/stable/'
      gpg: 'https://download.sublimetext.com/sublimehq-pub.gpg'

  packages:
    install:
      # List of apt packages to install. Will be installed with all required dependencies.
      list:
        # System and terminal tools
        - curl        # Command line tool for transferring data with URL syntax
        - default-jre # Java runtime
        - dia         # Diagram editor
        - exfat-fuse  # Read and write exFAT driver
        - exfat-utils # Utilities to create, check, label and dump exFAT file system 
        - htop        # Terminal system monitor
        - lhasa       # lzh unarchiver
        - mc          # Two panel terminal file manager
        - neofetch    # Shows Linux System Information with Distribution Logo
        - net-tools   # Base network tools
        - nfs-common  # Package for work with NFS shares
        - rar         # rar archiver
        - unrar       # rar unarchiver
        - unzip       # zip unarchiver
        - zip         # zip archiver
        - zsh         # zsh shell. Like bash, but better

        # Development
        - kexi                    # Visual DB editor
        - kexi-mysql-driver       # Kexi MySQL driver
        - kexi-postgresql-driver  # Kexi MySQL driver
        - sublime-merge           # Git GUI client
        - sublime-text            # Lightning fast code editor
       #- qtcreator               # QT IDE
          # Visual Studio code will be installed using ansible playbook

        # Internet
        - firefox              # From Mozilla team with <3
        - google-chrome-stable # Thing for collecting your personal data
        - telegram-desktop     # Text me, baby!
          # Skype will be installed from deb package
          # Slack will be installed from deb package
        
        # Office
        - evolution     # Ultimate email client
        - evolution-ews # Evolution EWS support
        - libreoffice   # Not best, but good office suite

        # Media
        - deepin-picker          # Color picker
        - deepin-screen-recorder # Screen recorder
        - flameshot              # Screenshot tool
        - inkscape               # Vector image editor
        - vlc                    # Ultimate video player that lays everything
       #- audacity               # Audio editing software

        # KDE-specific packages
        - gwenview        # Image browser
        - kdevelop        # IDE for C/C++ and other languages
        - kdevelop-php    # KDevelop PHP language support
        - kdevelop-python # KDevelop Python language support
        - kget            # Download manager
        - kmahjongg       # Game: Mahjongg
        - kmines          # Game: Minesweeper
        - knights         # Game: Chess
        - kompare         # Diff viewer
        - kpat            # Game: Solitaire 
        - krdc            # RDC/VNC viewer
        - krita           # Image editor
        - krusader        # Two-panel file manager
        - ktorrent        # Torrent downloader
        - kubuntu-restricted-addons # Commonly used restricted packages for Kubuntu
        - kubuntu-restricted-extras # Commonly used media codecs and fonts for Kubuntu
        - okular          # Document viewer
        - plasma-discover-backend-flatpak # Adds flatpak support to Discover package manager
        - plasma-discover-backend-snap    # Adds snap support to Discover package manager
       #- kdenlive        # Video editor for KDE

        # Look and feel customization packages
        - deepin-icon-theme
        - numix-blue-gtk-theme
        - numix-gtk-theme
        - numix-icon-theme
        - numix-icon-theme-circle
        - papirus-icon-theme

      # List of deb files that should be installed.
      deb:
        # XnViewMP image viewer.
        - https://download.xnview.com/XnViewMP-linux-x64.deb
        # Slack chat.
        - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.2.0-amd64.deb
        # Skype.
        - https://go.skype.com/skypeforlinux-64.deb
        # Zoom app.
        - https://zoom.us/client/latest/zoom_amd64.deb
        # Teamviewer.
        - https://download.teamviewer.com/download/linux/teamviewer_amd64.deb

# Section for offline dump.
# This section is used in `./offline-download.sh` script.
offline:
  # Drivers that needs to be downloaded and installed using `make && sudo make install`.
  drivers:
    - name: RTL8812AU
      repo: https://github.com/gordboy/rtl8812au-5.6.4.2
    - name: RTL8822BU
      repo: https://github.com/EntropicEffect/rtl8822bu
  
  # Offline deb files section.
  deb:
    # Following packages will be downloaded with all their dependencies to `./deb` directory.
    # Select kernels wisely because too recent kernel may not be compatible with drivers you want to download.
    list:
      - linux-image-5.3.0-26-generic         # Kernel itself 
      - linux-headers-5.3.0-26-generic       # Kernel C/C++ headers for compilers
      - linux-modules-5.3.0-26-generic       # Kernel modules
      - linux-modules-extra-5.3.0-26-generic # Kernel extra modules
      - ansible         # Ansible for being able to run playbooks
      - build-essential # C/C++ build tools, gcc compiler, etc
      - exfat-fuse      # Read and write exFAT driver
      - exfat-utils     # Utilities to create, check, label and dump exFAT filesystem 
      - net-tools       # Base network tools

    # Usually package has dependencies that has no install candidates. Exclude that kind of packages using grep filters.
    list_filters:
      - grep -v "^ "
      - grep -v "^debconf-"
      - grep -v "^kldutils$"
      - grep -v "^libc-dev$"
      - grep -v "^perl-openssl-abi-"
      - grep -v "^perlapi-"
      - grep -v "^python3-cffi-backend-api-"
