deb:
  download_dir: './deb'
  kernel: current # Current version of kernel retrieved by $(uname -r)
  list:
    - linux-image-{KERNEL}
    - linux-modules-{KERNEL}
    - linux-modules-extra-{KERNEL}
    - linux-headers-{KERNEL}
    - build-essential # C/C++ building tools.
    - exfat-fuse      # exFAT file system drivers.
    - exfat-utils     # exFAT file system tools.
    - net-tools       # Basic networking tools handy for setup.
    - dkms            # Dynamic Kernel Module Support Framework

drivers:
  download_dir: './drivers'
  list:
    # Asus USB AC56 WiFi dongle.
    - name: rtl8812au.zip
      url: https://codeload.github.com/gordboy/rtl8812au-5.6.4.2/zip/master
      install:
        - 'cd rtl8812au-5.6.4.2-master'
        - 'sudo make > /dev/null'
        - 'sudo make install'

    # Asus USB AC53 Nano WiFi dongle.
    - name: rtl8822bu.zip
      url: https://codeload.github.com/EntropicEffect/rtl8822bu/zip/master
      install:
        - 'cd rtl8822bu-master'
        - 'sudo make > /dev/null'
        - 'sudo make install'

    # xBox One gamepad.
    - name: xpadneo.zip
      url: https://codeload.github.com/atar-axis/xpadneo/zip/master
      install:
        - 'cd xpadneo-master'
        - 'sudo chmod +rwx install.sh'
        - 'sudo ./install.sh'
