version: "2.1"
services:
  cli:
    image: ${CLI_IMAGE:-docksal/cli:php7.3}
    volumes:
      - '~/.docksal/shared-config/php.ini:/etc/php/7.3/cli/conf.d/zzzz-php.ini'
      #- ${PROJECT_ROOT}/tmp/.cache/.composer:/home/docker/.composer:rw,cached
      #- ${PROJECT_ROOT}/tmp/.cache/.npm     :/home/docker/.npm:rw,cached
      #- ${PROJECT_ROOT}/tmp/.cache/.yarn    :/home/docker/.yarn:rw,cached
  db:
    image: ${DB_IMAGE:-docksal/db:mysql-5.7}
    command: --max_allowed_packet=128M
    volumes:
      - '~/.docksal/shared-config/my.cnf:/etc/my.cnf.d/zz_docksal.cnf'

  # Mailhog
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail

  # PHPMyAdmin
  pma:
    hostname: pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    labels:
      - io.docksal.virtual-host=pma.${VIRTUAL_HOST}
