---

- import_playbook: install-packages.yml
- import_playbook: install-php.yml
- import_playbook: install-composer-codesniffer.yml
- import_playbook: install-nvm.yml
- import_playbook: install-vscode.yml
- import_playbook: install-jetbrains-toolbox.yml
- import_playbook: configure-zsh.yml
- import_playbook: install-docksal.yml
