---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  tasks:
    - name: "Copy `home` directory from repo to user's home directoriy"
      copy:
        src: '../home/'
        dest: '$HOME'
        backup: no
