---

- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - ../config.yml

  tasks:
    - name: 'Adding apt keys...'
      loop: '{{ apt.repos }}'
      apt_key:
        url: '{{ item.gpg }}'
      when: item.gpg is defined

    - name: 'Adding PPA repositories...'
      loop: '{{ apt.repos }}'
      apt_repository:
        repo: '{{ item.repo }}'
        filename: '{{ item.filename }}'
        state: present
        update_cache: no

    - name: 'Installing packages from config.yml list...'
      apt:
        pkg: '{{ apt.packages.install.list }}'
        state: latest
        update_cache: yes

    - name: 'Installing DEB packages...'
      loop: '{{ apt.packages.install.deb }}'
      apt:
        deb: '{{ item }}'

