---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  tasks:
    - name: 'Visual Studio Code'
      include_role:
        name: ansible-role-visual-studio-code
      vars:
        users:
          - username: '{{ ansible_facts.user_id }}'
            visual_studio_code_extensions: '{{ vscode.plugins }}'
