---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  tasks:
    - name: Add Docker apt key
      become: yes
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'

    - name: 'Add Docker repository'
      become: yes
      apt_repository:
        repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
        filename: 'docker'
        state: present

    - name: Move Docker directory to ~/.docker
      become: yes
      copy:
        content: |
          {
            "graph": "/home/{{ ansible_facts.user_id }}/.docker"
          }
        dest: /etc/docker/daemon.json
        owner: '{{ ansible_facts.user_id }}'
        group : '{{ ansible_facts.user_id }}'
        mode: 755

    - name: 'Install Docker packages'
      become: yes
      apt:
        pkg:
          - docker-ce
          - docker-compose

    - name: Start Docker service on system boot
      become: yes
      service:
        name: docker
        enabled: yes
  
    - name: Restart Docker service
      become: yes
      service:
        name: docker
        state: restarted
