---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml 

  tasks:
    - name: Download composer
      become: yes
      get_url:
        url: https://getcomposer.org/composer-stable.phar
        dest: /usr/local/bin/composer
        mode: '0755'

    - name: Require drupal/coder globally
      command: composer global require drupal/coder  

    - name: Enable Drupal PHPCS standard
      file:
        state: link
        force: yes
        src: ~/.config/composer/vendor/drupal/coder/coder_sniffer/Drupal
        dest: ~/.config/composer/vendor/squizlabs/php_codesniffer/src/Standards/Drupal

    - name: Enable DrupalPractice PHPCS standard
      file:
        state: link
        force: yes
        src: ~/.config/composer/vendor/drupal/coder/coder_sniffer/DrupalPractice
        dest: ~/.config/composer/vendor/squizlabs/php_codesniffer/src/Standards/DrupalPractice