---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  tasks:
    - name: Make sure that "nodejs" package is removed
      become: yes
      apt:
        name: nodejs
        state: absent

    - name: Install node via nvm
      command: "zsh -c 'source $HOME/.zshrc && nvm install {{ node.version }} && nvm use {{ node.version }}'"
      when: zsh_antigen_configured is succeeded
      ignore_errors: yes

    - name: Install global npm packages
      command: "zsh -c 'source $HOME/.zshrc && npm install -g {{ node.npm.global | join(' ') }}'"
      when: zsh_antigen_configured is succeeded
      ignore_errors: yes
