---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  tasks:
    - name: Making sure that "nodejs" package is removed
      apt:
        name: nodejs
        state: absent

    - name: Remove ~/.nvm
      file:
        path: ~/.nvm
        state: absent
      when: node.install|bool

    - name: Install nvm
      raw: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
      when: node.install|bool

    - name: Install node v{{ node.version }}
      raw: '. ~/.nvm/nvm.sh && nvm install {{ node.version }}'
      when: node.install|bool

    - name: Install npm global packages
      raw: '. ~/.nvm/nvm.sh && npm --global install {{ node.npm.global|join(" ") }}'
      when: node.install|bool
