---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml 

  tasks:
    - name: Install Python packages
      become: yes
      apt:
        name:
          - python3-pip
          - python{{ python.version }}
          - python{{ python.version }}-dev
          - python{{ python.version }}-doc
          - python{{ python.version }}-minimal
      when: python.install|bool

    - name: Require global python3 packages
      command: pip3 install --user {{ python.pip3.global | join(' ') }}  
      when: python.install|bool
