---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  tasks:
    - name: 'Installing Visual Studio Code...'
      apt:
        name: code
      when: vscode.install|bool

    - name: 'Installing code extensions...'
      loop: '{{ vscode.plugins }}'
      command: 'code --install-extension {{ item }}'
      when: vscode.install|bool
