---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  tasks:
    # Run deb installation first as deb packages can add apt repos.
    - name: 'Install DEB packages'
      become: yes
      loop: '{{ apps.deb }}'
      apt:
        deb: '{{ item }}'

    - name: 'Add apt keys'
      become: yes
      loop: '{{ apps.repos }}'
      apt_key:
        url: '{{ item.gpg }}'
      when: item.gpg is defined

    - name: 'Add PPA repositories'
      become: yes
      loop: '{{ apps.repos }}'
      apt_repository:
        repo: '{{ item.repo }}'
        filename: '{{ item.filename }}'
        state: present
        update_cache: no

    - name: 'Install global packages'
      become: yes
      apt:
        pkg: '{{ apps.apt }}'
        state: present
        update_cache: yes

    - name: 'Install Gnome-specific packages'
      become: yes
      apt:
        pkg: '{{ gnome.apt.install }}'
        state: present
      when: gnome.apply|bool

    - name: 'Install KDE-specific packages'
      become: yes
      apt:
        pkg: '{{ kde.apt.install }}'
        state: present
      when: kde.apply|bool

    - name: 'Install snap packages'
      become: yes
      loop: '{{ apps.snap.install }}'
      snap:
        name: '{{ item.name }}'
        classic: '{{ item.classic | default("yes") }}'
        channel: '{{ item.channel | default("stable")}}'
        state: present
