---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml 

  tasks:
    - name: Install PHP packages
      become: yes
      apt:
        name:
          - php{{ php.version }}-common
          - php{{ php.version }}-cli
          - php{{ php.version }}-curl
          - php{{ php.version }}-gd
          - php{{ php.version }}-json
          - php{{ php.version }}-mbstring
          - php{{ php.version }}-mysql
          - php{{ php.version }}-opcache
          - php{{ php.version }}-xml
          - php{{ php.version }}-zip
      when: php.install|bool

    - name: Download composer
      become: yes
      get_url:
        url: https://getcomposer.org/composer-stable.phar
        dest: /usr/local/bin/composer
        mode: '0755'
      when: php.install|bool

    - name: Create ~/.composer if it does not exist
      file:
        path: $HOME/.composer
        state: directory
      when: php.install|bool

    - name: Require global composer packages
      command: composer global require {{ php.composer.global | join(' ') }}  
      when: php.install|bool

    - name: Enable Drupal PHPCS standard
      file:
        state: link
        src: $HOME/.composer/vendor/drupal/coder/coder_sniffer/Drupal
        dest: $HOME/.composer/vendor/squizlabs/php_codesniffer/src/Standards/Drupal
      when: php.install|bool and 'drupal/coder' in php.composer.global

    - name: Enable DrupalPractice PHPCS standard
      file:
        state: link
        src: $HOME/.composer/vendor/drupal/coder/coder_sniffer/DrupalPractice
        dest: $HOME/.composer/vendor/squizlabs/php_codesniffer/src/Standards/DrupalPractice
      when: php.install|bool and 'drupal/coder' in php.composer.global
