---

- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - ../config.yml

  tasks:
    - name: 'Add apt keys'
      loop: '{{ apt.repos }}'
      apt_key:
        url: '{{ item.gpg }}'
      when: item.gpg is defined

    - name: 'Add PPA repositories'
      loop: '{{ apt.repos }}'
      apt_repository:
        repo: '{{ item.repo }}'
        filename: '{{ item.filename }}'
        state: present
        update_cache: no

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: 'Install global packages'
      apt:
        pkg: '{{ apt.packages.install.list }}'
        state: present

    - name: 'Install gnome packages'
      apt:
        pkg: '{{ gnome.apt.install }}'
        state: present
      when: gnome.apply|bool

    - name: 'Install KDE packages'
      apt:
        pkg: '{{ kde.apt.install }}'
        state: present
      when: kde.apply|bool

    - name: 'Install DEB packages'
      loop: '{{ apt.packages.install.deb }}'
      apt:
        deb: '{{ item }}'
