---

- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - ../config.yml

  tasks:
    - name: Composer
      include_role:
        name: ansible-role-composer
      vars:
        composer_home_path: '~/.composer'
        composer_keep_updated: true
        composer_home_owner: "{{ ansible_facts.user_id }}"
        composer_home_group: "{{ ansible_facts.user_id }}"
        composer_global_packages:
          - name: "drupal/coder"
            release: "*"

    - name: Enable Drupal PHPCS standard
      file:
        state: link
        force: yes
        src: ~/.composer/vendor/drupal/coder/coder_sniffer/Drupal
        dest: ~/.composer/vendor/squizlabs/php_codesniffer/src/Standards/Drupal

    - name: Enable DrupalPractice PHPCS standard
      file:
        state: link
        force: yes
        src: ~/.composer/vendor/drupal/coder/coder_sniffer/DrupalPractice
        dest: ~/.composer/vendor/squizlabs/php_codesniffer/src/Standards/DrupalPractice