---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: '{{ ansible_facts.user_id }}'
          visual_studio_code_extensions: '{{ vscode.plugins }}'
          visual_studio_code_settings: '{{ vscode.settings }}'