---

- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - ../config.yml

  tasks:
    - name: 'Adding apt keys...'
      loop: '{{ apt.repos }}'
      apt_key:
        url: '{{ item.gpg }}'
      when: item.gpg is defined

    - name: 'Adding PPA repositories...'
      loop: '{{ apt.repos }}'
      apt_repository:
        repo: '{{ item.repo }}'
        filename: '{{ item.filename }}'
        state: present
        update_cache: no

    - name: 'Updating apt cache...'
      apt:
        update_cache: yes

    - name: 'Installing packages from config.yml list...'
      apt:
        pkg: '{{ apt.packages.install.list }}'

    - name: 'Installing DEB packages...'
      loop: '{{ apt.packages.install.deb }}'
      apt:
        deb: '{{ item }}'

    - name: 'Making sure that flatpak package is installed...'
      apt:
        pkg: 'flatpak'

    - name: 'Configuring flathub repo...'
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    
    - name: 'Installing flatpak packages...'
      become: yes
      loop: '{{ apt.packages.install.flathub }}'
      flatpak:
        name: '{{ item }}'
        remote: flathub
