---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  tasks:
    - name: Making sure that "nodejs" package is removed
      become: yes
      apt:
        name: nodejs
        state: absent

    - name: Create ~/.nvm directory
      file:
        path: ~/.nvm
        state: directory
        recurse: yes
        mode: '0755'

    - name: Node version manager
      include_role:
        name: ansible-role-nvm
      vars:
        nodejs_version: "{{ node.version }}"
        nvm_dir: "{{ ansible_env.HOME }}/.nvm"
        default: True
        nvm_commands:
          - "nvm alias service-default {{ node.version }}"
          - "nvm exec service-default npm install -g {{ node.npm.global | join(' ') }}"
