---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  tasks:
    - name: 'Install Visual Studio Code...'
      become: yes
      snap:
        name: code
        classic: yes
        channel: latest
        state: present
      when: vscode.install|bool

    - name: 'Install code extensions...'
      loop: '{{ vscode.plugins }}'
      command: 'code --install-extension {{ item }}'
      when: vscode.install|bool
