---

- import_playbook: copy-home-directory.yml
- import_playbook: install-zsh-antigen.yml
- import_playbook: install-packages.yml
- import_playbook: install-nvm.yml
- import_playbook: install-php.yml
- import_playbook: install-python.yml
- import_playbook: install-vscode.yml
- import_playbook: install-docker.yml
- import_playbook: install-docksal.yml
