---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../config.yml

  tasks:
    - name: 'Install apt-rdepends...'
      sudo: true
      apt:
        pkg: 'apt-rdepends'
        update_cache: true

    - name: 'Download deb packages with all dependencies for offline usage'
      raw: 'cd ../offline-cache/deb && apt-get download -q $(apt-rdepends {{ offline.deb.list | join(" ") }} | {{ offline.deb.list_filters | join(" | ") }} )'
